# Generated by Django 3.1.7 on 2021-03-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210222_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instalnk', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('autabout', models.TextField()),
            ],
        ),
    ]
